import { MenuItem } from './types';
import { Flame, Utensils, Zap } from 'lucide-react';

export const THEME_COLORS = {
  primary: '#ccff00', // Acid Green (ZZZ signature)
  secondary: '#ff4d00', // Warning Orange
  dark: '#0a0a0a',
  surface: '#18181b',
};

export const MENU_ITEMS: MenuItem[] = [
  {
    id: '01',
    name: 'Geprek Original',
    rank: 'S',
    element: 'Fire',
    price: 'Rp 15.000',
    category: 'Ayam Geprek',
    description: 'Sang legenda. Sambal bawang ulek dadakan dengan pedas yang nendang tanpa ampun.',
    image: './original.jpg',
    stats: { spiciness: 90, crunch: 85, portion: 70 },
  },
  {
    id: '02',
    name: 'Mozzarella Melt',
    rank: 'S',
    element: 'Cheese',
    price: 'Rp 22.000',
    category: 'Ayam Geprek',
    description: 'Pertahanan absolut. Lelehan keju mozzarella tebal menyelimuti kulit ayam yang super krispi.',
    image: './mozarella_melt.jpg',
    stats: { spiciness: 40, crunch: 80, portion: 90 },
  },
  {
    id: '03',
    name: 'Sambal Matah',
    rank: 'A',
    element: 'Garlic',
    price: 'Rp 18.000',
    category: 'Ayam Geprek',
    description: 'Serangan aromatik. Potongan serai, bawang, dan cabai segar yang bikin melek seketika.',
    image: './sambal_matah.jpg',
    stats: { spiciness: 65, crunch: 85, portion: 70 },
  },
  {
    id: '04',
    name: 'Fire Wings',
    rank: 'A',
    element: 'Fire',
    price: 'Rp 20.000',
    category: 'Menu Lain',
    description: 'Unit serangan udara. 6 potong sayap berbalut saus pedas membara. Awas panas!',
    image: './fire_wings.jpg',
    stats: { spiciness: 95, crunch: 60, portion: 60 },
  },
  {
    id: '05',
    name: 'Green Fury (Ijo)',
    rank: 'A',
    element: 'Toxic',
    price: 'Rp 16.000',
    category: 'Ayam Geprek',
    description: 'Efek "Toxic" yang nikmat. Cabai hijau segar dengan rasa gurih yang meresap ke tulang.',
    image: './green_fury_ijo.jpg',
    stats: { spiciness: 75, crunch: 85, portion: 70 },
  },
  {
    id: '06',
    name: 'Golden Yolk',
    rank: 'S',
    element: 'Physical',
    price: 'Rp 25.000',
    category: 'Ayam Geprek',
    description: 'Saus telur asin (Salted Egg) yang creamy dan rich. Gurihnya nembus pertahanan lidah.',
    image: './golden_yolk.jpg',
    stats: { spiciness: 20, crunch: 90, portion: 85 },
  },
  {
    id: '07',
    name: 'Volt Noodle Combo',
    rank: 'S',
    element: 'Electric',
    price: 'Rp 20.000',
    category: 'Paket',
    description: 'Recharge energimu. Combo maut Indomie + Geprek buat stamina full seharian.',
    image: './volt_noodle_combo.jpg',
    stats: { spiciness: 85, crunch: 60, portion: 100 },
  },
  {
    id: '08',
    name: 'Earth Shards',
    rank: 'B',
    element: 'Physical',
    price: 'Rp 10.000',
    category: 'Menu Lain',
    description: 'Kulit ayam goreng super renyah. Snack pelapis perut dengan kepadatan tinggi.',
    image: './earth_shards.jpg',
    stats: { spiciness: 10, crunch: 100, portion: 40 },
  },
  {
    id: '09',
    name: 'Fungal Strike',
    rank: 'B',
    element: 'Nature',
    price: 'Rp 12.000',
    category: 'Menu Lain',
    description: 'Jamur crispy anti-gagal. Luar garing, dalam kenyal. Cocok buat ngemil.',
    image: './fungal_strike.jpg',
    stats: { spiciness: 50, crunch: 95, portion: 50 },
  },
  {
    id: '10',
    name: 'Cryo Tea',
    rank: 'B',
    element: 'Ice',
    price: 'Rp 5.000',
    category: 'Minuman',
    description: 'Es Teh Manis. Pendingin sistem tubuh setelah pertempuran panas.',
    image: './cryo_tea.jpg',
    stats: { spiciness: 0, crunch: 0, portion: 100 },
  },
  {
    id: '11',
    name: 'Nitro Lemon',
    rank: 'A',
    element: 'Ice',
    price: 'Rp 12.000',
    category: 'Minuman',
    description: 'Lemon Squash soda. Hapus rasa berminyak dan pedas dalam satu tegukan.',
    image: './nitro_lemon.jpg',
    stats: { spiciness: 0, crunch: 0, portion: 80 },
  },
  {
    id: '12',
    name: 'Satay Crusher',
    rank: 'A',
    element: 'Earth',
    price: 'Rp 19.000',
    category: 'Ayam Geprek',
    description: 'Hantaman bumbu kacang. Perpaduan ayam geprek dengan saus sate yang legit.',
    image: './satay_crusher.jpg',
    stats: { spiciness: 30, crunch: 80, portion: 75 },
  },
];

export const ICONS = {
  Flame: <Flame size={20} />,
  Utensils: <Utensils size={20} />,
  Zap: <Zap size={20} />,
};